### ISSUE TITLE
Problem with integration - not working

### ISSUE THREAD

**Issue by koles142** [PiotrMachowski/Home-Assistant-custom-components-Antistorm#17]
Hi,

on the new HA 2022.11.2 - integration not working. In log I have:

Error while setting up antistorm platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/antistorm/sensor.py", line 40, in setup_platform
    city_name = request.json()['m']
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Could you check it?

Thanks

**Comment by PiotrMachowski** [comment]
Have you tried restarting HA?

**Comment by koles142** [comment]
Yes. I'm also restarted whole vm couple minutes ago. Still not working.

**Comment by koles142** [comment]
After update HA for newest version everything works fine.

**Comment by PiotrMachowski** [comment]
Great 👍
